sed -i s'/#gene/Ab_vf~~~#gene~~~annotation/'g sequences
sed -i s'/fbsA/Ab_vf~~~fbsA~~~Adherence/'g sequences
sed -i s'/fbsB/Ab_vf~~~fbsB~~~Adherence/'g sequences
sed -i s'/lmb/Ab_vf~~~lmb~~~Adherence/'g sequences
sed -i s'/PI-1_gbs0628/Ab_vf~~~PI-1_gbs0628~~~Adherence/'g sequences
sed -i s'/PI-1_gbs0629/Ab_vf~~~PI-1_gbs0629~~~Adherence/'g sequences
sed -i s'/PI-1_gbs0630/Ab_vf~~~PI-1_gbs0630~~~Adherence/'g sequences
sed -i s'/PI-1_gbs0631/Ab_vf~~~PI-1_gbs0631~~~Adherence/'g sequences
sed -i s'/PI-1_gbs0632/Ab_vf~~~PI-1_gbs0632~~~Adherence/'g sequences
sed -i s'/PI-2a_pilA/Ab_vf~~~PI-2a_pilA~~~Adherence/'g sequences
sed -i s'/PI-2a_pilB/Ab_vf~~~PI-2a_pilB~~~Adherence/'g sequences
sed -i s'/PI-2a_pilC/Ab_vf~~~PI-2a_pilC~~~Adherence/'g sequences
sed -i s'/PI-2a_srtC3/Ab_vf~~~PI-2a_srtC3~~~Adherence/'g sequences
sed -i s'/PI-2a_srtC4/Ab_vf~~~PI-2a_srtC4~~~Adherence/'g sequences
sed -i s'/cba/Ab_vf~~~cba~~~Antiphagocytosis/'g sequences
sed -i s'/cpsA/Ab_vf~~~cpsA~~~Antiphagocytosis/'g sequences
sed -i s'/cpsB/Ab_vf~~~cpsB~~~Antiphagocytosis/'g sequences
sed -i s'/cpsC/Ab_vf~~~cpsC~~~Antiphagocytosis/'g sequences
sed -i s'/cpsD/Ab_vf~~~cpsD~~~Antiphagocytosis/'g sequences
sed -i s'/cpsE/Ab_vf~~~cpsE~~~Antiphagocytosis/'g sequences
sed -i s'/cpsF/Ab_vf~~~cpsF~~~Antiphagocytosis/'g sequences
sed -i s'/cpsG/Ab_vf~~~cpsG~~~Antiphagocytosis/'g sequences
sed -i s'/cpsH/Ab_vf~~~cpsH~~~Antiphagocytosis/'g sequences
sed -i s'/cpsJ/Ab_vf~~~cpsJ~~~Antiphagocytosis/'g sequences
sed -i s'/cpsK/Ab_vf~~~cpsK~~~Antiphagocytosis/'g sequences
sed -i s'/cpsL/Ab_vf~~~cpsL~~~Antiphagocytosis/'g sequences
sed -i s'/cpsM/Ab_vf~~~cpsM~~~Antiphagocytosis/'g sequences
sed -i s'/cpsN/Ab_vf~~~cpsN~~~Antiphagocytosis/'g sequences
sed -i s'/cpsO/Ab_vf~~~cpsO~~~Antiphagocytosis/'g sequences
sed -i s'/neuA/Ab_vf~~~neuA~~~Antiphagocytosis/'g sequences
sed -i s'/neuB/Ab_vf~~~neuB~~~Antiphagocytosis/'g sequences
sed -i s'/neuC/Ab_vf~~~neuC~~~Antiphagocytosis/'g sequences
sed -i s'/neuD/Ab_vf~~~neuD~~~Antiphagocytosis/'g sequences
sed -i s'/hylB/Ab_vf~~~hylB~~~Exoenzyme/'g sequences
sed -i s'/scpB/Ab_vf~~~scpB~~~Immune evasion/'g sequences
sed -i s'/bca/Ab_vf~~~bca~~~Invasion/'g sequences
sed -i s'/cylE/Ab_vf~~~cylE~~~Toxin/'g sequences
sed -i s'/cfa/cfb/Ab_vf~~~cfa/cfb~~~Toxin/'g sequences
